import type { Metadata } from "next";
import "./globals.scss";

import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

import { Header } from "@/components";
import PrelineScript from "@/components/PrelineScript";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<PropsWithChildren<{}>>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gradient-to-r from-pink-300 via-purle-300 to-indigo-300`}
      >
        <Header />
        {children}
        <PrelineScript />
      </body>
    </html>
  );
}
