import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PrelineScript from '@/components/PrelineScript'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-pink-300 via-purle-300 to-indigo-300`}>
        <Header/>
        {children}</body>
      <PrelineScript/>
    </html>
  )
}
